# Generated by Django 3.2 on 2022-05-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Performances',
            new_name='Performance',
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='artisttype',
            options={'verbose_name_plural': 'ArtistTypes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name_plural': 'Performances'},
        ),
    ]
