# Generated by Django 3.2 on 2022-05-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_auto_20220519_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='performance',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performances.artist'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_title',
            field=models.CharField(max_length=254),
        ),
    ]
