# Generated by Django 3.2 on 2022-05-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='performances.artist'),
        ),
    ]
