# Generated by Django 3.2 on 2022-05-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_alter_product_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_description_short',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
