# Generated by Django 3.2 on 2022-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_artist_artist_description_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
