# Generated by Django 3.2 on 2022-07-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='order_total',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order',
            new_name='order_number',
        ),
    ]
